document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>底部文件</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/fotter.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'box_fotter\'>");
document.writeln("        <div class=\'box_fotter_top\'>");
document.writeln("            <p>相关合作伙伴</p>");
document.writeln("            <div>");
document.writeln("                <span>");
document.writeln("                    <a href=\'https://music.163.com/#/artist?id=13448775\'>");
document.writeln("                         <img src=\'../images/ximalaya.png\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                   ");
document.writeln("                </span>");
document.writeln("                <span>");
document.writeln("                    <a href=\'https://www.missevan.com/\'>");
document.writeln("                          <img src=\'../images/maoer.webp\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                  ");
document.writeln("                </span>");
document.writeln("                <span>");
document.writeln("                    <a href=\'https://www.jjwxc.net/\'>");
document.writeln("                         <img src=\'../images/jinjiang.webp\' alt=\'\'>");
document.writeln("                    </a>");
document.writeln("                </span>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'box_fotter_bottom\'>");
document.writeln("           ");
document.writeln("            <ul>");
document.writeln("                <li><a target=\'_blank\' title=\'随听介绍\' href=\'#\' rel=\'opener\'>公司介绍</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'关于我们\' href=\'#\' rel=\'opener\'>关于我们</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'随听动态\' href=\'#\' rel=\'opener\'>公司动态</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'联系我们\' href=\'#\' rel=\'opener\'>联系我们</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'反盗版盗链声明\' href=\'#\' rel=\'opener\'>反盗版盗链声明</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'个人信息保护政策\' href=\'#\' rel=\'opener\'>个人信息保护政策</a></li>");
document.writeln("                <li><a target=\'_blank\' title=\'下载中心\' href=\'#\' rel=\'opener\'>下载中心</a></li>");
document.writeln("            </ul>");
document.writeln("       <p>出品人:这里的糖没人吃  举报电话：12345678901 意见邮箱：3372900841@qq.com</p>");
document.writeln("       <p>杜绝虚假报道 欢迎社会监督</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    ");
document.writeln("</body>");
document.writeln("</html>");