document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>头部文件</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/header.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  ");
document.writeln("        <!-- 头部导航条 ：logo 首页  我的声音 下载客户端  搜索框 我的 历史 投稿 -->");
document.writeln("        <div class=\'header_nav\'>");
document.writeln("            <div class=\'nav_menus\'>");
document.writeln("                <div class=\'left_menus\'>");
document.writeln("                    <ul class=\'nav_menus_ul\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/index.html\'>首页</a>");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>我的声音</a>");
document.writeln("							");
document.writeln("						</li>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>下载客户端</a>");
document.writeln("						</li>");
document.writeln("                        <li>");
document.writeln("							<a href=\'#\'>关注</a>");
document.writeln("						</li>");
document.writeln("              	    </ul>");
document.writeln("				");
document.writeln("                </div>");
document.writeln("                <div class=\'serach_nav\'>");
document.writeln("                    <input type=\'text\' id=\'search_text\' autocomplete=\'off\' placeholder=\'广播剧｜音乐｜漫画｜小品\' value=\'\'>");
document.writeln("                    <span></span>");
document.writeln("                </div>");
document.writeln("                <!-- 选择登录 -->");
document.writeln("                <div class=\'xaunzedenglu\'>");
document.writeln("                    <a href=\'#\'>登录/注册</a>");
document.writeln("                </div>");
document.writeln("                <!-- 选择退出 -->");
document.writeln("                <div class=\'right_menus\'>");
document.writeln("                    <ul class=\'nav_menus_ul\'>");
document.writeln("						<li>");
document.writeln("							<a href=\'#\'>我的</a>");
document.writeln("                            <ul>");
document.writeln("                                <li><a href=\'#\'> <span class=\'my_introduce\'></span>我的主页</a></li>");
document.writeln("                                <li><a href=\'#\'> <span class=\'xinxi\'></span>消息中心</a></li>");
document.writeln("");
document.writeln("                                <li><a href=\'#\'> <span class=\'qianbao\'></span>我的钱包</a></li>");
document.writeln("                                <li><a href=\'#\'> <span class=\'shezhi\'></span>账号设置</a></li>");
document.writeln("                                <li class=\'tuichu_btn\'><a href=\'#\'> <span class=\'exit\'></span>退出</a></li>");
document.writeln("                            </ul>");
document.writeln("						</li>");
document.writeln("					");
document.writeln("						<li>");
document.writeln("							<a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/tougao.html\'>投稿</a>");
document.writeln("						</li>");
document.writeln("              	    </ul>");
document.writeln("				");
document.writeln("                </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'header_bottom\'>");
document.writeln("    ");
document.writeln("        </div>");
document.writeln("        </div>");
document.writeln("      <div class=\'header_nav_two\'>");
document.writeln("        <!-- <script src=\'../js/header.js\'></script> -->");
document.writeln("        <div class=\'wenhao\'>上午好</div>");
document.writeln("        <p>请开启你的随听之旅!</p>");
document.writeln("      </div>");
document.writeln("      <div class=\'box2\'>");
document.writeln("        <ul class=\'box2_ul\'>");
document.writeln("            <li><a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/index.html\'>发现声音</a></li>");
document.writeln("            <li><a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/guanboju.html\'>广播剧</a></li>");
document.writeln("            <li><a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/manhua.html\'>有声漫画</a></li>");
document.writeln("            <li><a href=\'#\'>听相声</a></li>");
document.writeln("            <li><a href=\'#\'>脱口秀</a></li>");
document.writeln("            <li><a href=\'#\'>小品</a></li>");
document.writeln("            <li><a href=\'#\'>小语种</a></li>");
document.writeln("            <li><a href=\'#\'>铃声</a></li>");
document.writeln("");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("   ");
document.writeln("</body>");
document.writeln("<script>");
document.writeln("");
document.writeln("window.addEventListener(\'load\',function(){");
document.writeln("    var box2_ul= document.querySelector(\'.box2_ul\');");
document.writeln("    var lis=box2_ul.querySelectorAll(\'li\');");
document.writeln("    var tuichu_btn = document.querySelector(\'.tuichu_btn\')");
document.writeln("    var right_menus = document.querySelector(\'.right_menus\')");
document.writeln("    var xaunzedenglu = document.querySelector(\'.xaunzedenglu\')");
document.writeln("    var tuichu_btn = document.querySelector(\'.tuichu_btn\')");
document.writeln("   //点击切换按钮的颜色和变化");
document.writeln("    for(let i = 0; i < lis.length; i++){");
document.writeln("        lis[i].onclick = function(){");
document.writeln("            for(let i = 0; i<lis.length;i++){");
document.writeln("                ");
document.writeln("                lis[i].style.backgroundColor = \'\'");
document.writeln("            }");
document.writeln("            this.style.backgroundColor=\'#f45b41\';");
document.writeln("            ");
document.writeln("        }");
document.writeln("    }");
document.writeln("    //分时间问候");
document.writeln("    var wenhao=document.querySelector(\'.wenhao\');");
document.writeln("        // 得到当前的小时数");
document.writeln("        var date=new Date();");
document.writeln("        var h=date.getHours();");
document.writeln("        if(h<12){");
document.writeln("            ");
document.writeln("            wenhao.innerHTML=\'早上好，今天也要加油哦！\';");
document.writeln("        }else if(h<18){");
document.writeln("            ");
document.writeln("            wenhao.innerHTML=\'下午好，今天辛苦啦！\';");
document.writeln("        }else{");
document.writeln("         ");
document.writeln("            wenhao.innerHTML=\'晚上好，晚上好好休息啦！\';");
document.writeln("        };");
document.writeln("        //点击退出登录");
document.writeln("        tuichu_btn.onclick = function(){");
document.writeln("            xaunzedenglu.style.display=\'block\'");
document.writeln("            right_menus.style.display=\'none\'");
document.writeln("        }");
document.writeln("        xaunzedenglu.onclick= function(){");
document.writeln("            window.location.href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/login.html\'");
document.writeln("        }");
document.writeln("})");
document.writeln("");
document.writeln("</script>");
document.writeln("</html>");