document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <title>头部文件2</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../css/header.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\'header_nav\'>");
document.writeln("        <div class=\'nav_menus\'>");
document.writeln("            <div class=\'left_menus\'>");
document.writeln("                <ul class=\'nav_menus_ul\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/index.html\'>首页</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>我的声音</a>");
document.writeln("                        ");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>下载客户端</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>关注</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("            ");
document.writeln("            </div>");
document.writeln("            <div class=\'serach_nav\'>");
document.writeln("                <input type=\'text\' id=\'search_text\' autocomplete=\'off\' placeholder=\'广播剧｜音乐｜漫画｜小品\' value=\'\'>");
document.writeln("                <span></span>");
document.writeln("            </div>");
document.writeln("            <div class=\'right_menus\'>");
document.writeln("                <ul class=\'nav_menus_ul\'>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>我的</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a href=\'#\'> <span class=\'my_introduce\'></span>我的主页</a></li>");
document.writeln("                            <li><a href=\'#\'> <span class=\'xinxi\'></span>消息中心</a></li>");
document.writeln("");
document.writeln("                            <li><a href=\'#\'> <span class=\'qianbao\'></span>我的钱包</a></li>");
document.writeln("                            <li><a href=\'#\'> <span class=\'shezhi\'></span>账号设置</a></li>");
document.writeln("                            <li><a href=\'#\'> <span class=\'exit\'></span>退出</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                ");
document.writeln("                    <li>");
document.writeln("                        <a href=\'http://127.0.0.1:8848/web%E5%BC%80%E5%8F%91%E4%BD%9C%E5%93%81/html/tougao.html\'>投稿</a>");
document.writeln("                    </li>");
document.writeln("                  </ul>");
document.writeln("            ");
document.writeln("            </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'header_bottom\'>");
document.writeln("");
document.writeln("    </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");